# RuneRogue Environment Setup Script
# This script helps set up the .env file with proper values

Write-Host "🌍 RuneRogue Environment Setup" -ForegroundColor Green
Write-Host "==============================" -ForegroundColor Green

# Check if .env already exists
if (Test-Path ".env") {
    Write-Host "⚠️  .env file already exists!" -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite it? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "❌ Setup cancelled." -ForegroundColor Red
        exit
    }
}

Write-Host ""
Write-Host "📝 Setting up environment variables..." -ForegroundColor Blue
Write-Host "Press Enter to skip optional variables" -ForegroundColor Gray
Write-Host ""

# GitHub Token
Write-Host "🔑 GitHub Personal Access Token" -ForegroundColor Cyan
Write-Host "   Used for: GitHub MCP server, repository operations"
Write-Host "   Get one at: https://github.com/settings/tokens"
$githubToken = Read-Host "   Enter your GitHub token (optional)"

# Tavily API Key
Write-Host ""
Write-Host "🔍 Tavily API Key" -ForegroundColor Cyan
Write-Host "   Used for: Web search and research capabilities"
Write-Host "   Get one at: https://tavily.com/"
$tavilyKey = Read-Host "   Enter your Tavily API key (optional)"

# Discord Configuration
Write-Host ""
Write-Host "🤖 Discord Configuration" -ForegroundColor Cyan
Write-Host "   Used for: Discord Activities and bot integration"
$discordToken = Read-Host "   Discord Bot Token (optional)"
$discordClientId = Read-Host "   Discord Client ID (optional)"

# Database Configuration
Write-Host ""
Write-Host "💾 Database Configuration" -ForegroundColor Cyan
$dbUrl = Read-Host "   Database URL (default: sqlite:./runerogue.db)"
if (-not $dbUrl) { $dbUrl = "sqlite:./runerogue.db" }

$redisUrl = Read-Host "   Redis URL (default: redis://localhost:6379)"
if (-not $redisUrl) { $redisUrl = "redis://localhost:6379" }

# Server Configuration
Write-Host ""
Write-Host "🚀 Server Configuration" -ForegroundColor Cyan
$port = Read-Host "   Server Port (default: 3000)"
if (-not $port) { $port = "3000" }

$nodeEnv = Read-Host "   Node Environment (default: development)"
if (-not $nodeEnv) { $nodeEnv = "development" }

# Economy API
Write-Host ""
Write-Host "💰 Economy API Configuration" -ForegroundColor Cyan
$economyUrl = Read-Host "   Economy API URL (default: http://localhost:8080)"
if (-not $economyUrl) { $economyUrl = "http://localhost:8080" }

$economyKey = Read-Host "   Economy API Key (optional)"

# Create .env file
Write-Host ""
Write-Host "📄 Creating .env file..." -ForegroundColor Blue

$envContent = @"
# RuneRogue Environment Configuration
# Generated by setup-environment.ps1

# GitHub MCP Server
GITHUB_PERSONAL_ACCESS_TOKEN=$githubToken
MCP_GITHUB_TOKEN=$githubToken

# Tavily Search MCP Server
TAVILY_API_KEY=$tavilyKey

# Discord Bot Configuration
DISCORD_BOT_TOKEN=$discordToken
DISCORD_CLIENT_ID=$discordClientId

# Database Configuration
DATABASE_URL=$dbUrl
REDIS_URL=$redisUrl

# Game Server Configuration  
PORT=$port
NODE_ENV=$nodeEnv

# Economy API Configuration
ECONOMY_API_URL=$economyUrl
ECONOMY_API_KEY=$economyKey

# MCP Server Configuration
MCP_SERVER_PORT=3001
MCP_LOG_LEVEL=info

# Generated on: $(Get-Date)
"@

$envContent | Out-File -FilePath ".env" -Encoding UTF8

Write-Host "✅ .env file created successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "🔧 Next steps:" -ForegroundColor Yellow
Write-Host "   1. Edit .env file to add any missing API keys"
Write-Host "   2. Run: .\verify-complete-setup.ps1"
Write-Host "   3. Open mcp-repos.code-workspace in VS Code"
Write-Host ""
Write-Host "🎮 Start development:" -ForegroundColor Green
Write-Host "   cd server-ts && npm run dev" 