# Exported from Render on 2025-06-02T03:11:24Z
services:
- type: web
  name: runerogue
  runtime: node
  repo: https://github.com/Giftedx/runerogue
  plan: free
  envVars:
  - key: REDIS_URL
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: JWT_SECRET_KEY
    sync: false
  - key: COLYSEUS_WS_PORT
    sync: false
  - key: SESSION_SECRET
    sync: false
  - key: DISCORD_BOT_TOKEN
    sync: false
  - key: DISCORD_REDIRECT_URI
    sync: false
  - key: DISCORD_CLIENT_SECRET
    sync: false
  - key: DISCORD_CLIENT_ID
    sync: false
  - key: PORT
    sync: false
  - key: NODE_ENV
    sync: false
  region: frankfurt
  buildCommand: npm install && npm run build
  startCommand: npm start
  autoDeployTrigger: commit
version: "1"
