apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: runerogueprime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
      - name: ai-service
        image: runerogueprime-ai-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: runerogueprime-secrets
              key: GEMINI_API_KEY
