apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: runerogueprime
spec:
  selector:
    app: ai-service
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: ClusterIP
