apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: runerogueprime
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: ClusterIP
