apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: runerogueprime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: runerogueprime-auth-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: runerogueprime-secrets
              key: JWT_SECRET
