apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server
  namespace: runerogueprime
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      containers:
      - name: game-server
        image: runerogueprime-game-server:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3002"
        - name: AI_SERVICE_URL
          value: "http://ai-service:3003"
