apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: runerogueprime-ingress
  namespace: runerogueprime
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: runerogueprime.example.com
    http:
      paths:
      - path: /game/(.*)
        pathType: Prefix
        backend:
          service:
            name: game-server
            port:
              number: 3000
      - path: /auth/(.*)
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 3002
      - path: /ai/(.*)
        pathType: Prefix
        backend:
          service:
            name: ai-service
            port:
              number: 3003
