debug: false
dry_run: false
log_level: INFO
timeout: 30
port: 5000
log_to_file: false

# Self-Building Configuration
self_build_enabled: true
self_build_risk_threshold: medium
self_build_approval_required: high
metrics_collection_interval: 60
improvement_suggestion_frequency: weekly

# AWS Configuration
aws:
  region: us-east-1
  
# SendGrid Configuration  
sendgrid:
  api_key: ${SENDGRID_API_KEY}
  from_email: noreply@runerogue.com

# Scraping Configuration
scraping:
  user_agent: "RuneRogue Bot 1.0"
  max_retries: 3
  delay_between_requests: 1