name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: your-gcp-project-id # Replace with your GCP Project ID
  GAR_LOCATION: us-central1 # Replace with your desired Google Artifact Registry location

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Google Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
        username: _json_key
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build and push game-server
      uses: docker/build-push-action@v5
      with:
        context: ./backend/game-server
        push: true
        tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/runescape-rogue-prime/game-server:latest

    - name: Build and push api-gateway
      uses: docker/build-push-action@v5
      with:
        context: ./backend/api-gateway
        push: true
        tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/runescape-rogue-prime/api-gateway:latest

    - name: Build and push auth-service
      uses: docker/build-push-action@v5
      with:
        context: ./backend/auth-service
        push: true
        tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/runescape-rogue-prime/auth-service:latest

    - name: Build and push ai-service
      uses: docker/build-push-action@v5
      with:
        context: ./backend/ai-service
        push: true
        tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/runescape-rogue-prime/ai-service:latest

    - name: Build and push telemetry-aggregator
      uses: docker/build-push-action@v5
      with:
        context: ./backend/telemetry-aggregator
        push: true
        tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/runescape-rogue-prime/telemetry-aggregator:latest
