apiVersion: apps/v1
kind: Deployment
metadata:
  name: runerogue-app
  namespace: runerogue
  labels:
    app: runerogue
    component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: runerogue
      component: web
  template:
    metadata:
      labels:
        app: runerogue
        component: web
    spec:
      serviceAccountName: runerogue-app
      containers:
      - name: runerogue
        image: runerogue:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: PORT
          value: "5000"
        - name: DEBUG
          value: "false"
        - name: DRY_RUN
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: runerogue-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: runerogue-secrets
              key: redis-url
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: runerogue-secrets
              key: sendgrid-api-key
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: runerogue-secrets
              key: jwt-secret-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: runerogue-config
      imagePullSecrets:
      - name: gcr-secret