apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - secret.yaml
  - rbac.yaml
  - hpa.yaml

namePrefix: runerogue-
namespace: runerogue

commonLabels:
  app: runerogue
  version: v1.0.0

images:
  - name: runerogue
    newTag: latest
