name: Agentic Copilot Assignment

on:
  issues:
    types: [labeled, opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to assign'
        required: true

jobs:
  assign-to-copilot:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issues' && (contains(github.event.issue.labels.*.name, 'copilot') || contains(github.event.issue.labels.*.name, 'ai-task'))) ||
      github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run advanced assignment script
        env:
          GITHUB_TOKEN: ${{ secrets.AGENTIC_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            python scripts/agentic_copilot.py ${{ github.event.inputs.issue_number }}
          else
            python scripts/agentic_copilot.py ${{ github.event.issue.number }}
          fi
      
      - name: Report results
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.issue_number || github.event.issue.number }};
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `## Agentic Copilot Assignment
              
              The automated assignment process has been completed.
              
              If GitHub Copilot has not been assigned to this issue, please check:
              
              1. The GitHub Copilot app is properly installed in this repository
              2. The \`AGENTIC_GITHUB_TOKEN\` secret has sufficient permissions
              3. GitHub Copilot Agent service is available and properly configured
              
              You can manually run the assignment workflow from the Actions tab if needed.`
            });
