name: Assign Copilot on Labeled Issues

on:
  issues:
    types: [labeled]
  # Uncomment the following to support pull requests too
  # pull_request:
  #   types: [labeled]

jobs:
  assign-copilot:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'copilot'
    steps:
      - name: Assign Copilot to the Issue
        uses: actions/github-script@v7
        with:
          script: |
            // Using the GitHub Copilot SWE Agent
            const assignee = 'Copilot';
            const issueNumber = context.payload.issue ? context.payload.issue.number : context.payload.pull_request.number;
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              assignees: [assignee],
            });
