name: Auto Assign Issues to Copilot

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  auto-assign-copilot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install @octokit/rest
      - name: Auto-assign issues to Copilot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name || github.repository.split('/')[1] }}
          PLACEHOLDER_ASSIGNEE: 'Giftedx'
          COPILOT_ASSIGNEE: 'github-copilot'
          LABEL: 'copilot-agent'
        run: node .github/scripts/auto_assign_copilot.js
