name: Documentation & Memory Hygiene

on:
  pull_request:
    paths:
      - "src/**"
      - "agents/**"
      - "economy/**"
      - "economy_api/**"
      - "tests/**"
      - "!docs/ROADMAP.md"
      - "!docs/MEMORIES.md"
  push:
    branches: [main, master]
    paths:
      - "src/**"
      - "agents/**"
      - "economy/**"
      - "economy_api/**"
      - "tests/**"
      - "!docs/ROADMAP.md"
      - "!docs/MEMORIES.md"

jobs:
  doc-memory-hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for doc/memory hygiene
        run: bash scripts/check-doc-memory-hygiene.sh
